### PR TITLE
Add autoconf files

### PR DESCRIPTION
**Pull request by aelmahmoudy**
I suggest using autoconf rather than cmake build system

### CODE REVIEW

**Comment by linostar** [comment]
Any particular reason for choosing autoconf over cmake?

**Comment by aelmahmoudy** [comment]
Most commonly used.Support for libtool for proper library  versioning

**Comment by linostar** [comment]
Ok, in that case, please edit the installation method in README.md accordingly, and update this pull request with the new commit.

**Comment by aelmahmoudy** [comment]
Do you mean that you don't mind replacing cmake with autoconf? 
Note that autoconf and cmake can coexist together. 
Also I still didn't autoconf new_method as it seems still not integrated yet into libitl. And it still doesn't build the demos, I think the demos can be built in 'make test' ?

**Comment by linostar** [comment]
I prefer we leave the cmake installation option, and allow autoconf installation method that you added. But since autoconf installation is now possible, you better document it in README.md as well.

As for the demos, they seem not written to be run as automated tests from what I saw, but it's not too hard to change them to serve that purpose. It will be great if you can do the necessary changes so that they become suitable for a make test command.

**Comment by aelmahmoudy** [comment]
Done.
I didn't  modify the demos,I just used them as they are for make check target.
Also I still didn't add new_method to autoconf

**Pull request merged**
